name: build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    # CAMBIO AQUÍ: Usamos la versión "mínima" para intentar coger un servidor libre antes
    runs-on: ubuntu-24.04-core
    
    steps:
    # 1. Descarga tu código
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Instala dependencias
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip git device-tree-compiler

    # 3. Instala pmbootstrap desde el código fuente
    - name: Install pmbootstrap from source
      run: |
        pip3 install --user setuptools
        git clone https://gitlab.com/postmarketOS/pmbootstrap.git
        cd pmbootstrap
        python3 setup.py install --user
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cd ..

    # 4. Inicializa pmbootstrap
    - name: Initialize pmbootstrap
      run: |
        yes | pmbootstrap -y \
          --work /tmp/pmbootstrap_work \
          --aports ${{ github.workspace }} \
          init

    # 5. Compila
    - name: Build rootfs for gts7fewifi
      run: |
        pmbootstrap config device gts7fewifi
        pmbootstrap config manufacturer Samsung
        pmbootstrap config kernel local
        pmbootstrap build --strict linux-gts7fewifi
        pmbootstrap install --no-ccache --sdcard=/tmp/pmos-image.img
      
    # 6. Sube la imagen
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: pmos-gts7fewifi-image
        path: /tmp/pmos-image.img
