name: Build T733
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: my-ports
      - name: Build Image
        run: |
          sudo apt update && sudo apt install -y git openssl parted qemu-user-static
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          git clone https://gitlab.postmarketos.org/postmarketOS/pmaports.git
          cp -rv my-ports/device/testing/* pmaports/device/testing/
          mkdir -p ~/.config/pmbootstrap
          cat > ~/.config/pmbootstrap/v3.cfg <<'EOF'
          [pmbootstrap]
          aports = /home/runner/work/pmaports-gts7fewifi/pmaports-gts7fewifi/pmaports
          device = samsung-gts7fewifi
          ui = console
          work = /tmp/pmbootstrap
          is_custom_channel = False
          cfg_version = 3
          EOF
          cd pmbootstrap
           ./pmbootstrap.py --work /tmp/pmbootstrap --aports $GITHUB_WORKSPACE/pmaports zap -p
           ./pmbootstrap.py --work /tmp/pmbootstrap --aports $GITHUB_WORKSPACE/pmaports -y install --no-sshd
           ./pmbootstrap.py --work /tmp/pmbootstrap --aports $GITHUB_WORKSPACE/pmaports export
          ls -lh /tmp/postmarketOS-export/
      - name: Upload IMG
        uses: actions/upload-artifact@v4
        with:
          name: gts7fewifi-console-img
          path: /tmp/postmarketOS-export/*
